language: node_js

node_js:
  - "8"

addons:
  - chrome: stable

services:
  - svfb

before_script:
  - export DISPLAY=:99.0
  - npm start > /dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - npm run test-ci
  - grunt coverage
